### ISSUE TITLE
UnicodeDecodeError while parsing BDF input file

### ISSUE THREAD

**Issue by a3an-de** [makutamoto/bdf-to-image#1]
bdftoimg terminates with UnicodeDcodeError.

/home/a3/PycharmProjects/pythonProject/venv/bin/python /home/a3/PycharmProjects/pythonProject/bdftoimg.py /home/a3/Documents/bdf-to-image-master/shnm6x12r.png out.img
Traceback (most recent call last):
  File "/home/a3/PycharmProjects/pythonProject/bdftoimg.py", line 38, in <module>
    inputData = f.read()
  File "/usr/lib/python3.8/codecs.py", line 322, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x89 in position 0: invalid start byte

I guessed, a BDF file is basically a hex file, so I changed with 'open(inputFile) as f:' to 'with open(inputFile, 'rb') as f:'
That did not help either, Regex seems to have problems with hex data.

Traceback (most recent call last):
  File "/home/a3/PycharmProjects/pythonProject/bdftoimg.py", line 48, in <module>
    for char in clauseRegex.finditer(inputData):
TypeError: cannot use a string pattern on a bytes-like object

Any thoughts an this problem ?

Cheers, Adrian

**Comment by a3an-de** [comment]
Sorry, my mistake.. Using a png file as input ....
